import Footer from "@/components/Footer/Footer"
import Header from "@/components/Header/Header"
import { Metadata } from "next"

export const metadata: Metadata = {
  title: {
    default: 'Next.js tutorial',
    // добавление суфикса "| tutorial" к заголовкам "title" в шаблонах
    template: '%s tutorial',
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
